site_name: REPACSS User Guide
site_url: https://talkingjupiter.github.io/repacss-user-guide/
use_directory_urls: false # This is for only TalkingJupiter's fork
site_description: Official documentation for the REPACSS HPC cluster at Texas Tech University
site_author: REPACSS Team

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/images/Favicon.svg
  favicon: assets/images/Favicon.svg
  features:
    - search.suggest
    - content.footer.last-updated
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      timezone: America/Chicago
      locale: en
      
extra_css:
  - assets/stylesheets/extra.css

repo_name: nsfcac/repacss-user-guide
repo_url: https://github.com/nsfcac/repacss-user-guide
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  # - Getting Started: getting-started-at-REPACSS.md
  - Absolute Beginner Guide: absolute-beginner-guide.md

  - Connecting to REPACSS:
      - Overview: connecting/index.md
      - VPN: connecting/vpn.md
      - MFA Setup: connecting/mfa.md
      - VSCode SSH: connecting/vscode.md

  - Running Jobs:
      - Job Basics: running-jobs/basics.md
      - Job Examples: running-jobs/examples.md
      - Determine Resource Needs: running-jobs/determining-resource-requirements.md
      - Interactive Sessions: running-jobs/interactive.md
      - Scheduling: running-jobs/scheduling.md
      - Monitoring: running-jobs/monitoring.md
      - Best Practices: running-jobs/best-practices.md

  - Understanding Our Systems:
      - Architecture: understanding/repacss-system/architecture.md
      # - Timeline: understanding/repacss-system/timeline.md
      # - Known Issues: understanding/repacss-system/known-issues.md
      # - Vendor Bugs: understanding/repacss-system/vendor-bugs.md
      - File System:
        - File Transfer: understanding/repacss-system/file-system/file-transfer.md
        - File Permissions: understanding/repacss-system/file-system/unix-permissions.md 
        - Sharing File Access: understanding/repacss-system/file-system/ACL.md

  - Getting and Managing Your Account:
      - Overview: account/index.md
      - TTU: account/ttu.md
      # - ACCESS: account/access.md
      - Passwords: account/passwords.md
      # - Policy: account/policy.md
      
  - Software:
      - Module System: software/module-system.md
      # - Available Software: software/available-software.md
      - Installing Packages: software/installing-packages.md
      - Conda: software/conda.md

  - Performance:
      - Compiler Flags: performance/compiler-flags.md
      # - Profiling Tools: performance/profiling-tools.md
      # - Scaling Tests: performance/scaling-tests.md

  - Resources:
      - Glossary: reference/glossary.md
      - Cheatsheet: reference/cheatsheet.md
      - Common Errors: reference/common-errors.md
      - FAQ: faq.md
      - Contact Us: support.md
      